// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhotoApp.Api;

#nullable disable

namespace PhotoApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhotoApp.Api.DbObjects.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentMediaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("ParentMediaId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MainFolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MainFolderId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MainFolderId1");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.ProjectFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHeadFolder")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.ProjectWebDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverPhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FontFamily")
                        .HasColumnType("text");

                    b.Property<int?>("FontLayout")
                        .HasColumnType("integer");

                    b.Property<int?>("FontSize")
                        .HasColumnType("integer");

                    b.Property<int?>("FontWeight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoverPhotoId");

                    b.ToTable("WebDesignes");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.Project_ProjectWebDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Device")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectWebDesignId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectWebDesignId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId1");

                    b.HasIndex("ProjectWebDesignId");

                    b.HasIndex("ProjectWebDesignId1");

                    b.HasIndex("ProjectId", "Device")
                        .IsUnique();

                    b.ToTable("Project_ProjectWebDesigns");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailLoginCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailLoginCodeExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.Media", b =>
                {
                    b.HasOne("PhotoApp.Api.DbObjects.ProjectFolder", "ParentFolder")
                        .WithMany("Medias")
                        .HasForeignKey("ParentFolderId");

                    b.HasOne("PhotoApp.Api.DbObjects.Media", "ParentMedia")
                        .WithMany("ConnectedMedias")
                        .HasForeignKey("ParentMediaId");

                    b.HasOne("PhotoApp.Api.DbObjects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("ParentFolder");

                    b.Navigation("ParentMedia");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.Project", b =>
                {
                    b.HasOne("PhotoApp.Api.DbObjects.ProjectFolder", "MainFolder")
                        .WithMany()
                        .HasForeignKey("MainFolderId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoApp.Api.DbObjects.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainFolder");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.ProjectFolder", b =>
                {
                    b.HasOne("PhotoApp.Api.DbObjects.ProjectFolder", "ParentFolder")
                        .WithMany("Folders")
                        .HasForeignKey("ParentFolderId");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.ProjectWebDesign", b =>
                {
                    b.HasOne("PhotoApp.Api.DbObjects.Media", "CoverPhoto")
                        .WithMany()
                        .HasForeignKey("CoverPhotoId");

                    b.Navigation("CoverPhoto");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.Project_ProjectWebDesign", b =>
                {
                    b.HasOne("PhotoApp.Api.DbObjects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoApp.Api.DbObjects.Project", null)
                        .WithMany("WebDesignAssignments")
                        .HasForeignKey("ProjectId1");

                    b.HasOne("PhotoApp.Api.DbObjects.ProjectWebDesign", "ProjectWebDesign")
                        .WithMany()
                        .HasForeignKey("ProjectWebDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoApp.Api.DbObjects.ProjectWebDesign", null)
                        .WithMany("WebDesignAssignments")
                        .HasForeignKey("ProjectWebDesignId1");

                    b.Navigation("Project");

                    b.Navigation("ProjectWebDesign");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.RefreshToken", b =>
                {
                    b.HasOne("PhotoApp.Api.DbObjects.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.Media", b =>
                {
                    b.Navigation("ConnectedMedias");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.Project", b =>
                {
                    b.Navigation("WebDesignAssignments");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.ProjectFolder", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Medias");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.ProjectWebDesign", b =>
                {
                    b.Navigation("WebDesignAssignments");
                });

            modelBuilder.Entity("PhotoApp.Api.DbObjects.User", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
