<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\video\**" />
    <Content Remove="wwwroot\video\**" />
    <EmbeddedResource Remove="wwwroot\video\**" />
    <None Remove="wwwroot\video\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\jpg\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\AuthStyles.css" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotoApp.Common\PhotoApp.Common.csproj" />
  </ItemGroup>

</Project>
